# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://deelobo.github.io/web/
title: Diele's website
email: lobo0010@umn.edu
author: Diele Lobo
description: > # "Write an awesome description for your new site here.
  I am a doctoral candidate in Conservation Science at the University of Minnesota. My research and teaching interests center around the social dimensions of biodiversity conservation and social-ecological resilience to global environmental change.
copyright: 'Copyright &copy; 2020 Diele Lobo. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/dielelobo
  - title: cv
    url: https://deelobo.github.io/cv/
